pub const SYS_READ: usize = 0;
pub const SYS_WRITE: usize = 1;
pub const SYS_OPEN: usize = 2;
pub const SYS_CLOSE: usize = 3;
pub const SYS_STAT: usize = 4;
pub const SYS_FSTAT: usize = 5;
pub const SYS_POLL: usize = 7;
pub const SYS_KILL: usize = 62;
pub const SYS_UNAME: usize = 63;
pub const SYS_IOCTL: usize = 16;
pub const SYS_WRITEV: usize = 20;
pub const SYS_GETCWD: usize = 79;
pub const SYS_CHDIR: usize = 80;
pub const SYS_TIMES: usize = 100;
pub const SYS_GETUID: usize = 102;
pub const SYS_GETEUID: usize = 107;
pub const SYS_GETEGID: usize = 108;
pub const SYS_SETPGID: usize = 109;
pub const SYS_GETPPID: usize = 110;
pub const SYS_GETPGID: usize = 121;
pub const SYS_SETUID: usize = 105;
pub const SYS_SETGID: usize = 106;
pub const SYS_MMAP: usize = 9;
pub const SYS_MPROTECT: usize = 10;
pub const SYS_MUNMAP: usize = 11;
pub const SYS_BRK: usize = 12;
pub const SYS_RT_SIGACTION: usize = 13;
pub const SYS_RT_SIGPROCMASK: usize = 14;
pub const SYS_LSTAT: usize = 6;
pub const SYS_LSEEK: usize = 8;
pub const SYS_FCNTL: usize = 72;
pub const SYS_OPENAT: usize = 257;
pub const SYS_NANOSLEEP: usize = 35;
pub const SYS_ARCH_PRCTL: usize = 158;
pub const SYS_SET_TID_ADDRESS: usize = 218;
pub const SYS_GETDENTS64: usize = 217;
pub const SYS_CLOCK_GETTIME: usize = 228;
pub const SYS_TIME: usize = 201;
pub const SYS_READLINKAT: usize = 267;
pub const SYS_SET_ROBUST_LIST: usize = 273;
pub const SYS_PRLIMIT64: usize = 302;
pub const SYS_GETRANDOM: usize = 318;
pub const SYS_RSEQ: usize = 334;
pub const SYS_NEWFSTATAT: usize = 262;
pub const SYS_GETGID: usize = 104;
pub const SYS_GETPID: usize = 39;
pub const SYS_FORK: usize = 57;
pub const SYS_EXECVE: usize = 59;
pub const SYS_EXIT: usize = 60;
pub const SYS_WAIT4: usize = 61;
pub const SYS_SCHED_YIELD: usize = 24;
pub const SYS_EXIT_GROUP: usize = 231;
pub const SYS_SHUTDOWN: usize = 500;

pub const MAX_SYSCALL: usize = 512;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(usize)]
pub enum Syscall {
    Read = SYS_READ,
    Write = SYS_WRITE,
    Open = SYS_OPEN,
    Close = SYS_CLOSE,
    Stat = SYS_STAT,
    Fstat = SYS_FSTAT,
    Poll = SYS_POLL,
    Kill = SYS_KILL,
    Uname = SYS_UNAME,
    Ioctl = SYS_IOCTL,
    Writev = SYS_WRITEV,
    Getcwd = SYS_GETCWD,
    Chdir = SYS_CHDIR,
    Times = SYS_TIMES,
    Getuid = SYS_GETUID,
    Geteuid = SYS_GETEUID,
    Getegid = SYS_GETEGID,
    Setpgid = SYS_SETPGID,
    Getppid = SYS_GETPPID,
    Getpgid = SYS_GETPGID,
    Setuid = SYS_SETUID,
    Setgid = SYS_SETGID,
    Mmap = SYS_MMAP,
    Mprotect = SYS_MPROTECT,
    Munmap = SYS_MUNMAP,
    Brk = SYS_BRK,
    RtSigaction = SYS_RT_SIGACTION,
    RtSigprocmask = SYS_RT_SIGPROCMASK,
    Lstat = SYS_LSTAT,
    Lseek = SYS_LSEEK,
    Fcntl = SYS_FCNTL,
    Openat = SYS_OPENAT,
    Nanosleep = SYS_NANOSLEEP,
    ArchPrctl = SYS_ARCH_PRCTL,
    SetTidAddress = SYS_SET_TID_ADDRESS,
    Getdents64 = SYS_GETDENTS64,
    ClockGettime = SYS_CLOCK_GETTIME,
    Time = SYS_TIME,
    Readlinkat = SYS_READLINKAT,
    SetRobustList = SYS_SET_ROBUST_LIST,
    Prlimit64 = SYS_PRLIMIT64,
    Getrandom = SYS_GETRANDOM,
    Rseq = SYS_RSEQ,
    Newfstatat = SYS_NEWFSTATAT,
    Getgid = SYS_GETGID,
    Getpid = SYS_GETPID,
    Fork = SYS_FORK,
    Execve = SYS_EXECVE,
    Exit = SYS_EXIT,
    Wait4 = SYS_WAIT4,
    SchedYield = SYS_SCHED_YIELD,
    ExitGroup = SYS_EXIT_GROUP,
    Shutdown = SYS_SHUTDOWN,
}

impl Syscall {
    pub const fn number(self) -> usize {
        self as usize
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Read => "read",
            Self::Write => "write",
            Self::Open => "open",
            Self::Close => "close",
            Self::Stat => "stat",
            Self::Fstat => "fstat",
            Self::Poll => "poll",
            Self::Kill => "kill",
            Self::Uname => "uname",
            Self::Ioctl => "ioctl",
            Self::Writev => "writev",
            Self::Getcwd => "getcwd",
            Self::Chdir => "chdir",
            Self::Times => "times",
            Self::Getuid => "getuid",
            Self::Geteuid => "geteuid",
            Self::Getegid => "getegid",
            Self::Setpgid => "setpgid",
            Self::Getppid => "getppid",
            Self::Getpgid => "getpgid",
            Self::Setuid => "setuid",
            Self::Setgid => "setgid",
            Self::Mmap => "mmap",
            Self::Mprotect => "mprotect",
            Self::Munmap => "munmap",
            Self::Brk => "brk",
            Self::RtSigaction => "rt_sigaction",
            Self::RtSigprocmask => "rt_sigprocmask",
            Self::Lstat => "lstat",
            Self::Lseek => "lseek",
            Self::Fcntl => "fcntl",
            Self::Openat => "openat",
            Self::Nanosleep => "nanosleep",
            Self::ArchPrctl => "arch_prctl",
            Self::SetTidAddress => "set_tid_address",
            Self::Getdents64 => "getdents64",
            Self::ClockGettime => "clock_gettime",
            Self::Time => "time",
            Self::Readlinkat => "readlinkat",
            Self::SetRobustList => "set_robust_list",
            Self::Prlimit64 => "prlimit64",
            Self::Getrandom => "getrandom",
            Self::Rseq => "rseq",
            Self::Newfstatat => "newfstatat",
            Self::Getgid => "getgid",
            Self::Getpid => "getpid",
            Self::Fork => "fork",
            Self::Execve => "execve",
            Self::Exit => "exit",
            Self::Wait4 => "wait4",
            Self::SchedYield => "sched_yield",
            Self::ExitGroup => "exit_group",
            Self::Shutdown => "shutdown",
        }
    }

    pub const fn arg_count(self) -> usize {
        match self {
            Self::Read => 3,
            Self::Write => 3,
            Self::Open => 2,
            Self::Close => 1,
            Self::Stat => 2,
            Self::Fstat => 2,
            Self::Poll => 3,
            Self::Kill => 2,
            Self::Uname => 1,
            Self::Ioctl => 3,
            Self::Writev => 3,
            Self::Getcwd => 2,
            Self::Chdir => 1,
            Self::Times => 0,
            Self::Getuid => 0,
            Self::Geteuid => 0,
            Self::Getegid => 0,
            Self::Setpgid => 2,
            Self::Getppid => 0,
            Self::Getpgid => 1,
            Self::Setuid => 1,
            Self::Setgid => 1,
            Self::Mmap => 6,
            Self::Mprotect => 3,
            Self::Munmap => 2,
            Self::Brk => 1,
            Self::RtSigaction => 4,
            Self::RtSigprocmask => 4,
            Self::Lstat => 2,
            Self::Lseek => 3,
            Self::Fcntl => 3,
            Self::Openat => 4,
            Self::Nanosleep => 2,
            Self::ArchPrctl => 2,
            Self::SetTidAddress => 1,
            Self::Getdents64 => 3,
            Self::ClockGettime => 2,
            Self::Time => 0,
            Self::Readlinkat => 4,
            Self::SetRobustList => 2,
            Self::Prlimit64 => 4,
            Self::Getrandom => 3,
            Self::Rseq => 4,
            Self::Newfstatat => 4,
            Self::Getgid => 0,
            Self::Getpid => 0,
            Self::Fork => 0,
            Self::Execve => 3,
            Self::Exit => 1,
            Self::Wait4 => 4,
            Self::SchedYield => 0,
            Self::ExitGroup => 1,
            Self::Shutdown => 0,
        }
    }

    pub const fn from_number(number: usize) -> Option<Self> {
        match number {
            SYS_READ => Some(Self::Read),
            SYS_WRITE => Some(Self::Write),
            SYS_OPEN => Some(Self::Open),
            SYS_CLOSE => Some(Self::Close),
            SYS_STAT => Some(Self::Stat),
            SYS_FSTAT => Some(Self::Fstat),
            SYS_POLL => Some(Self::Poll),
            SYS_KILL => Some(Self::Kill),
            SYS_UNAME => Some(Self::Uname),
            SYS_IOCTL => Some(Self::Ioctl),
            SYS_WRITEV => Some(Self::Writev),
            SYS_GETCWD => Some(Self::Getcwd),
            SYS_CHDIR => Some(Self::Chdir),
            SYS_TIMES => Some(Self::Times),
            SYS_GETUID => Some(Self::Getuid),
            SYS_GETEUID => Some(Self::Geteuid),
            SYS_GETEGID => Some(Self::Getegid),
            SYS_SETPGID => Some(Self::Setpgid),
            SYS_GETPPID => Some(Self::Getppid),
            SYS_GETPGID => Some(Self::Getpgid),
            SYS_SETUID => Some(Self::Setuid),
            SYS_SETGID => Some(Self::Setgid),
            SYS_MMAP => Some(Self::Mmap),
            SYS_MPROTECT => Some(Self::Mprotect),
            SYS_MUNMAP => Some(Self::Munmap),
            SYS_BRK => Some(Self::Brk),
            SYS_RT_SIGACTION => Some(Self::RtSigaction),
            SYS_RT_SIGPROCMASK => Some(Self::RtSigprocmask),
            SYS_LSTAT => Some(Self::Lstat),
            SYS_LSEEK => Some(Self::Lseek),
            SYS_FCNTL => Some(Self::Fcntl),
            SYS_OPENAT => Some(Self::Openat),
            SYS_NANOSLEEP => Some(Self::Nanosleep),
            SYS_ARCH_PRCTL => Some(Self::ArchPrctl),
            SYS_SET_TID_ADDRESS => Some(Self::SetTidAddress),
            SYS_GETDENTS64 => Some(Self::Getdents64),
            SYS_CLOCK_GETTIME => Some(Self::ClockGettime),
            SYS_TIME => Some(Self::Time),
            SYS_READLINKAT => Some(Self::Readlinkat),
            SYS_SET_ROBUST_LIST => Some(Self::SetRobustList),
            SYS_PRLIMIT64 => Some(Self::Prlimit64),
            SYS_GETRANDOM => Some(Self::Getrandom),
            SYS_RSEQ => Some(Self::Rseq),
            SYS_NEWFSTATAT => Some(Self::Newfstatat),
            SYS_GETGID => Some(Self::Getgid),
            SYS_GETPID => Some(Self::Getpid),
            SYS_FORK => Some(Self::Fork),
            SYS_EXECVE => Some(Self::Execve),
            SYS_EXIT => Some(Self::Exit),
            SYS_WAIT4 => Some(Self::Wait4),
            SYS_SCHED_YIELD => Some(Self::SchedYield),
            SYS_EXIT_GROUP => Some(Self::ExitGroup),
            SYS_SHUTDOWN => Some(Self::Shutdown),
            _ => None,
        }
    }
}
